#!/bin/bash
# Run our parser on all the footprint files we found so far GitHub
set -eu
set -o pipefail

test_dir=dist/build
temp_dir=$test_dir/parse-tmp
kicad_mod_dir=$temp_dir/kicad-data
kicad_mod_output_dir=$temp_dir/mod-output
test_executable=$test_dir/parse
root_dir=$(pwd)

mkdir -p $test_dir
mkdir -p $temp_dir

if [ ! -d "$kicad_mod_dir" ]; then
  git clone "https://github.com/kitspace/kicad_footprints" "$kicad_mod_dir"
  cd "$kicad_mod_dir" && ./init
else
  cd "$kicad_mod_dir"
fi
cd "$root_dir"

echo "Compiling."
stack exec -- ghc tests/Parse.hs -threaded -tmpdir "$temp_dir" -o "$test_executable"

"$test_executable" "$kicad_mod_dir" +RTS -N

python kicad_footprint_load.py "$kicad_mod_output_dir"
